AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Deliforce web test Lambda for PIpeline Integration'
Globals:
  Function:
    Environment:
      Variables:
        bucketName: testuser-constant
        constantFileName: constant.json
Resources:
  ApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: Developement
      DefinitionUri: ./deliforceserver-favascr47.yml
  DeliforcebackgroundjobMethod:
     Type: AWS::Serverless::Function
     Properties:
       FunctionName: backGroundjoboneee
       Timeout: 300
       Handler: index.handler
       Runtime: nodejs8.10
       CodeUri: ./backGroundjob/backGroundjob.zip
       Policies: AWSLambdaFullAccess
       Role: arn:aws:iam::120107595195:role/favas-poc
       

  DeliforcebackgroundjobtwoMethod:
     Type: AWS::Serverless::Function
     Properties:
       FunctionName: smsoneee
       Timeout: 300
       Handler: index.handler
       Runtime: nodejs8.10
       CodeUri: ./sms/sms.zip
       Policies: AWSLambdaFullAccess
       Role: arn:aws:iam::120107595195:role/favas-poc
       
  
  
  

  
